kind: pipeline
type: docker
name: docker dry run

trigger:
  event:
    - push

steps:
  - name: docker publish dry-run
    image: plugins/docker
    pull: always
    settings:
      repo: pierreiexec/voucher-deployer
      dockerfile: Dockerfile
      dry_run: true

---
kind: pipeline
type: docker
name: docker rebuild latest

trigger:
  event:
    - cron
    - promote
  target:
    - latest
    - next

steps:
  - name: set tag latest
    image: bash
    commands:
      - echo -n "latest," > .tags
    when:
      target:
        - latest

  - name: set tag next
    image: bash
    commands:
      - echo -n "next," > .tags
    when:
      target:
        - next

  - name: set date tag
    image: bash
    commands:
      - date -u -Iseconds | sed 's/+00:00//g' | sed 's/:/-/g' >> .tags

  - name: docker publish latest
    image: plugins/docker
    pull: always
    settings:
      repo: pierreiexec/voucher-deployer
      dockerfile: Dockerfile
      username:
        from_secret: docker-user
      password:
        from_secret: docker-token
